version: '3.3'
services:
  evepraisal:
    container_name: evepraisal
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080
      - 8090:8090
    volumes:
      - ./db:/evepraisal/db
      - ./evepraisal.toml:/evepraisal/evepraisal.toml:ro
    restart: always
